// apps/docs/src/components/react/canvas-qrcode-example.tsx
import {CanvasQRCode, type QRCodeCanvasOptions} from '@qrcodesdk/react';

export default function CanvasQRCodeExample() {
  const options: QRCodeCanvasOptions = {
    size: 8,
    margin: 4,
    colors: {
      colorDark: '#111827',
      colorLight: '#ffffff',
    },
  };

  return <CanvasQRCode data="https://qrcodesdk.dev" options={options} />;
}

// apps/docs/src/components/angular/canvas-qrcode-example.ts
import {Component} from '@angular/core';

import {CanvasQRCode, type QRCodeCanvasOptions} from '@qrcodesdk/angular';

@Component({
  selector: 'AngularCanvasQRCodeExample',
  imports: [CanvasQRCode],
  template: `
    <canvas-qrcode [options]="options" data="https://qrcodesdk.dev" />
  `,
})
export class CanvasQRCodeExample {
  options: QRCodeCanvasOptions = {
    size: 8,
    margin: 4,
    colors: {
      colorDark: '#111827',
      colorLight: '#ffffff',
    },
  };
}
