// packages/angular/projects/angular/src/lib/CanvasQRCode.ts
import { isPlatformBrowser } from '@angular/common';
import {
  Component,
  PLATFORM_ID,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  Renderer2,
} from '@angular/core';
import { type QRCodeMatrixOptions, qrcode } from '@qrcodesdk/core';

import { CanvasQRCodeRenderer, type QRCodeCanvasRendererOptions } from '@qrcodesdk/browser';

import { replaceElementChildren } from './render-element';

export type QRCodeCanvasOptions = QRCodeMatrixOptions & QRCodeCanvasRendererOptions;

@Component({
  selector: 'canvas-qrcode',
  template: '',
})
export class CanvasQRCode {
  private readonly renderer = inject(Renderer2);
  private readonly isBrowser = isPlatformBrowser(inject(PLATFORM_ID));
  private readonly qrcode = inject(ElementRef);

  data = input.required<string>();

  options = input<QRCodeCanvasOptions>();

  readonly canvasRenderer = computed(() => CanvasQRCodeRenderer(this.options()));

  readonly qrcodeBuilder = computed(() => {
    const options = this.options();
    return qrcode(this.data())
      .version(options?.version)
      .errorCorrection(options?.errorCorrectionLevel)
      .mode(options?.mode)
      .mask(options?.mask)
      .renderer(this.canvasRenderer());
  });

  constructor() {
    effect(() => {
      if (!this.isBrowser) return;

      const canvas = this.qrcodeBuilder().render();

      replaceElementChildren(this.renderer, this.qrcode, canvas);
    });
  }
}

// packages/react/src/CanvasQRCode.tsx
import {CanvasQRCodeRenderer, type QRCodeCanvasRendererOptions} from '@qrcodesdk/browser';
import {type QRCodeMatrixOptions} from '@qrcodesdk/core';
import {useEffect, useMemo, useRef} from 'react';

import {replaceElementChildren} from './replace-children';
import type {QRCodeBaseProps} from './types';
import {qrcode} from '@qrcodesdk/core';

export type QRCodeCanvasOptions = QRCodeMatrixOptions & QRCodeCanvasRendererOptions;

export type CanvasQRCodeProps = QRCodeBaseProps<QRCodeCanvasOptions>;

export function CanvasQRCode({data, options, className}: CanvasQRCodeProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRenderer = useMemo(() => CanvasQRCodeRenderer(options), [options]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    replaceElementChildren(container, qrcode(data).config(options).render(canvasRenderer));
  }, [canvasRenderer, data, options]);

  return <div className={className} ref={containerRef} />;
}
