// packages/svelte/src/lib/QRCodeCanvas.svelte
<script lang="ts">
  import {QRCodeCanvasRenderer} from '@qrcodesdk/browser';
  import {qrcode} from '@qrcodesdk/core';

  import type {QRCodeCanvasProps} from './types.js';

  let {data, options, ...attributes}: QRCodeCanvasProps = $props();
  let container = $state<HTMLDivElement>();

  const canvasRenderer = $derived(QRCodeCanvasRenderer(options));

  $effect(() => {
    if (!container) return;

    container.replaceChildren(qrcode(data).config(options).render(canvasRenderer));
  });
</script>

<div bind:this={container} {...attributes}></div>

// packages/react/src/QRCodeCanvas.tsx
import {type QRCodeCanvasOptions, QRCodeCanvasRenderer} from '@qrcodesdk/browser';
import {qrcode} from '@qrcodesdk/core';
import {useEffect, useMemo, useRef} from 'react';

import type {QRCodeBaseProps} from './types';

export type QRCodeCanvasProps = QRCodeBaseProps<QRCodeCanvasOptions>;

export function QRCodeCanvas({data, options, className}: QRCodeCanvasProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRenderer = useMemo(() => QRCodeCanvasRenderer(options), [options]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    container.replaceChildren(qrcode(data).config(options).render(canvasRenderer));
  }, [canvasRenderer, data, options]);

  return <div className={className} ref={containerRef} />;
}
