// packages/svelte/src/lib/QRCodeImage.svelte
<script lang="ts">
  import {QRCodeDownloadImageRenderer, QRCodeImageRenderer} from '@qrcodesdk/browser';
  import {qrcode} from '@qrcodesdk/core';

  import type {QRCodeImageProps} from './types.js';

  let {data, options, ...attributes}: QRCodeImageProps = $props();
  let container = $state<HTMLDivElement>();

  const imageRenderer = $derived(QRCodeImageRenderer(options));

  $effect(() => {
    if (!container) return;

    container.replaceChildren(qrcode(data).config(options).render(imageRenderer));
  });

  export function download(filename = '') {
    if (typeof document === 'undefined') return;

    qrcode(data)
      .config(options)
      .render(
        QRCodeDownloadImageRenderer({renderer: imageRenderer, filename: filename || undefined}),
      );
  }
</script>

<div bind:this={container} {...attributes}></div>

// packages/react/src/QRCodeImage.tsx
import {
  QRCodeDownloadImageRenderer,
  type QRCodeImageOptions,
  QRCodeImageRenderer,
} from '@qrcodesdk/browser';
import {qrcode} from '@qrcodesdk/core';
import {forwardRef, useEffect, useImperativeHandle, useMemo, useRef} from 'react';

import type {QRCodeBaseProps, QRCodeDownloadHandle} from './types';

export type QRCodeImageProps = QRCodeBaseProps<QRCodeImageOptions>;

export const QRCodeImage = forwardRef<QRCodeDownloadHandle, QRCodeImageProps>(function QRCodeImage(
  {data, options, className},
  ref,
) {
  const containerRef = useRef<HTMLDivElement>(null);
  const imageRenderer = useMemo(() => QRCodeImageRenderer(options), [options]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    container.replaceChildren(qrcode(data).config(options).render(imageRenderer));
  }, [data, imageRenderer, options]);

  useImperativeHandle(
    ref,
    () => ({
      download(filename?: string) {
        qrcode(data)
          .config(options)
          .render(
            QRCodeDownloadImageRenderer({
              renderer: imageRenderer,
              filename,
            }),
          );
      },
    }),
    [data, imageRenderer, options],
  );

  return <div className={className} ref={containerRef} />;
});
