// packages/svelte/runtime/smoke-consumer.svelte
<script lang="ts">
  import {VERSION} from 'svelte/compiler';

  import {QRCodeCanvas, QRCodeImage, QRCodeSVG} from '@qrcodesdk/svelte';

  const options = {style: {moduleSize: 2, quietZone: 1}};
  const imageOptions = {
    ...options,
    accessibility: {
      alt: 'Framework runtime QR code',
      ariaLabel: 'Framework runtime QR code',
    },
  };
</script>

<main>
  <p data-testid="framework-version">Svelte {VERSION}</p>
  <section data-testid="qrcode-svg">
    <QRCodeSVG payload="HELLO" {options} />
  </section>
  <section data-testid="qrcode-image">
    <QRCodeImage payload="HELLO" options={imageOptions} />
  </section>
  <section data-testid="qrcode-canvas">
    <QRCodeCanvas payload="HELLO" {options} />
  </section>
</main>

// packages/angular/runtime/smoke-consumer.ts
import {Component, VERSION} from '@angular/core';

import {QRCodeCanvas, QRCodeImage, QRCodeSVG} from '@qrcodesdk/angular';

@Component({
  selector: 'app-root',
  imports: [QRCodeSVG, QRCodeImage, QRCodeCanvas],
  template: `
    <main>
      <p data-testid="framework-version">Angular {{ frameworkVersion }}</p>
      <section data-testid="qrcode-svg">
        <qrcode-svg [options]="options" payload="HELLO" />
      </section>
      <section data-testid="qrcode-image">
        <qrcode-image [options]="imageOptions" payload="HELLO" />
      </section>
      <section data-testid="qrcode-canvas">
        <qrcode-canvas [options]="options" payload="HELLO" />
      </section>
    </main>
  `,
})
export class App {
  protected readonly frameworkVersion = VERSION.full;
  protected readonly options = {style: {moduleSize: 2, quietZone: 1}};
  protected readonly imageOptions = {
    ...this.options,
    accessibility: {
      alt: 'Framework runtime QR code',
      ariaLabel: 'Framework runtime QR code',
    },
  };
}
