// apps/docs/src/components/angular/download-image-qrcode-example.ts
import {Component, viewChild} from '@angular/core';

import {ImageQRCode} from '@qrcodesdk/angular';

@Component({
  selector: 'AngularImageQRCodeDownloadExample',
  imports: [ImageQRCode],
  template: `
    <div class="flex flex-col items-center">
      <image-qrcode
        #qrcode
        [options]="{
          alt: 'QR code for qrcodesdk.dev',
        }"
        data="https://qrcodesdk.dev" />
      <button class="btn-primary" (click)="qrcode.download('qrcodesdk')" type="button">
        Download PNG
      </button>
    </div>
  `,
})
export class DownloadImageQrcodeExample {
  private readonly qrCode = viewChild.required(ImageQRCode);

  protected download() {
    this.qrCode().download('qrcode.png');
  }
}

// apps/docs/src/components/react/download-image-qrcode-example.tsx
import {useRef} from 'react';

import {ImageQRCode, type ImageQRCodeHandle} from '@qrcodesdk/react';

export default function DownloadImageQRCodeExample() {
  const qrcode = useRef<ImageQRCodeHandle>(null);

  return (
    <div className="flex flex-col items-center">
      <ImageQRCode
        data="https://qrcodesdk.dev"
        options={{
          alt: 'QR code for qrcodesdk.dev',
        }}
        ref={qrcode}
      />
      <button
        className="btn-primary"
        onClick={() => qrcode.current?.download('qrcodesdk')}
        type="button">
        Download PNG
      </button>
    </div>
  );
}
