// apps/docs/src/components/vue/qrcode-image-example.vue
<script setup lang="ts">
import type {QRCodeImageOptions} from '@qrcodesdk/browser';
import {QRCodeImage} from '@qrcodesdk/vue';

const options: QRCodeImageOptions = {
  size: 8,
  margin: 4,
  alt: 'QR code for qrcodesdk.dev',
  ariaLabel: 'Scan to open qrcodesdk.dev',
};
</script>

<template>
  <QRCodeImage data="https://qrcodesdk.dev" :options="options" />
</template>

// apps/docs/src/components/react/qrcode-image-example.tsx
import type {QRCodeImageOptions} from '@qrcodesdk/browser';
import {QRCodeImage} from '@qrcodesdk/react';

export default function QRCodeImageExample() {
  const options: QRCodeImageOptions = {
    size: 8,
    margin: 4,
    alt: 'QR code for qrcodesdk.dev',
    ariaLabel: 'Scan to open qrcodesdk.dev',
  };

  return <QRCodeImage data="https://qrcodesdk.dev" options={options} />;
}
