// apps/docs/src/components/vue/qrcode-canvas-example.vue
<script setup lang="ts">
import type {QRCodeCanvasOptions} from '@qrcodesdk/browser';
import {QRCodeCanvas} from '@qrcodesdk/vue';

const options: QRCodeCanvasOptions = {
  size: 8,
  margin: 4,
  colors: {
    colorDark: '#111827',
    colorLight: '#ffffff',
  },
};
</script>

<template>
  <QRCodeCanvas data="https://qrcodesdk.dev" :options />
</template>

// apps/docs/src/components/react/qrcode-canvas-example.tsx
import type {QRCodeCanvasOptions} from '@qrcodesdk/browser';
import {QRCodeCanvas} from '@qrcodesdk/react';

export default function QRCodeCanvasExample() {
  const options: QRCodeCanvasOptions = {
    size: 8,
    margin: 4,
    colors: {
      colorDark: '#111827',
      colorLight: '#ffffff',
    },
  };

  return <QRCodeCanvas data="https://qrcodesdk.dev" options={options} />;
}
